# tasks file for bash
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ bash_dependencies }}"
  tags:
    - configuration
    - bash
    - bash-dependencies

- name: create configuration file - .bashrc
  template:
    src: etc/skel/.bashrc.j2
    dest: "{{ item.value.dest }}/.bashrc"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default(item.value.owner) | default('root') }}"
    mode: "{{ item.value.mode | default('0644') }}"
  with_dict: "{{ bash_bashrc_destinations }}"
  tags:
    - configuration
    - bash
    - bash-configuration

- name: create configuration file - .bash_aliases
  template:
    src: etc/skel/.bash_aliases.j2
    dest: "{{ item.value.dest }}/.bash_aliases"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default(item.value.owner) | default('root') }}"
    mode: "{{ item.value.mode | default('0644') }}"
  with_dict: "{{ bash_bashrc_destinations }}"
  tags:
    - configuration
    - bash
    - bash-configuration
